# Generated by Django 5.2.7 on 2025-10-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_price', models.IntegerField(unique=True)),
                ('product_info', models.CharField(max_length=255)),
                ('sklad', models.BooleanField(default=False)),
                ('product_size', models.IntegerField(unique=True)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
