# Generated by Django 5.2.7 on 2025-10-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Products',
        ),
    ]
