# Generated by Django 5.2.7 on 2025-10-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_rename_person_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='work',
            field=models.BooleanField(default=False),
        ),
    ]
