# Generated by Django 5.2.7 on 2025-10-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_students_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.IntegerField(max_length=40),
        ),
    ]
