# Generated by Django 5.2.7 on 2025-10-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_students_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
    ]
